champions = {
    'kayle': 'tld',
    'swain': 'fob',
    'pantheon': 'tld',
    'karthus': 'tld',
    'singed': 'fob',
    'urgot': 'tld',
    'malphite': 'fob',
    'sion': 'fob',
    'akali': 'fob',
    'mordekaiser': 'fob',
    'rengar': 'fob',
    'jax': 'tld',
    'teemo': 'tld',
    'kennen': 'tld',
    'jarvan iv': 'fob',
    'yasuo': 'fob',
    'kled': 'fob',
    'poppy': 'fob',
    'illaoi': 'tld',
    'tryndamere': 'ss',
    'irelia': 'tld',
    'jayce': 'tld',
    'nautilis': 'fob',
    'rumble': 'fob',
    'darius': 'fob',
    'rammus': 'fob',
    'renekton': 'tld',
    'heimerdinger': 'tld',
    'olaf': 'ss',
    'graves': 'tld',
    'fiora': 'fob',
    'maokai': 'fob',
    'garen': 'fob',
    'trundle': 'tld',
    'aatrox': 'tld',
    'gangplank': 'tld',
    'dr. mundo': 'fob',
    'nasus': 'fob',
    'volibear': 'fob',
    'xin zhao': 'fob',
    'gnar': 'tld',
    'lissandra': 'tld',
    'ekko': 'fob',
    'tahm kench': 'tld',
    'cho’gath': 'fob',
    'shen': 'fob',
    'vladimir': 'tld',
    'yorick': 'fob',
    'ryze':  'tld',
    'quinn': 'dodge',
    'galio': 'fob',
    'wukong': 'tld',
}

def masteries(champions):
	champions=raw_input('Who are you against: ')
	print champions[key]
